### ISSUE TITLE
randomNumber 是不是有问题

### ISSUE THREAD

**Issue by zyvas** [leizongmin/node-lei-utils#1]
```
> lei.randomNumber(3)
'526'
> lei.randomNumber(3)
'191'
> lei.randomNumber(3)
'81'
> lei.randomNumber(3)
'715'
```

是不是不满足要求了？

`Math.floor(Math.random() * max_num)` 的范围在 `0` 到 `max_num - 1`

`’0123456789‘.length + 1` 就是 11 了 `code_string[10]` 不应该吧？

同 `randomString` 和 `randomLetter`

**Comment by leizongmin** [comment]
已修正：https://github.com/leizongmin/node-lei-utils/commit/3cac2705c1c4be9ed8799c95e756c7710a12259f

看看是否满意

**Comment by zyvas** [comment]
棒棒的
